library(ggplot2)
str(mpg)
qplot(displ, hwy, data=mpg)
qplot(displ, hwy, data=mpg, color=drv)
qplot(displ, hwy, data=mpg, geom=c("point", "smooth"))
qplot(hwy, data=mpg, fill=drv)
qplot(displ, hwy, data=mpg, facets=.~drv)
qplot(hwy, data=mpg, facets=drv~., binwidth=2)
testdat <- data.frame(x=1:100, y=rnorm(100))
testdat[50,2] <- 100
plot(testdat$x, testdat$y, type='l', ylim=c(-3,3))
g <- ggplot(testdat, aes(x=x, y=y))
g+geom_line()
g+geom_line() + ylim(-3,3)
g+geom_line() + coord_cartesian(ylim=c(-3,3))
library(nlme)
library(lattice)
xyplot(weight ~ Time | Diet, BodyWeight)
library(lattice)
library(datasets)
data(airquality)
p <- xyplot(Ozone ~ Wind | factor(Month), data = airquality)
qplot(Ozone, Wind, data = airquality)+geom_smooth()
